/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HeaderRouteImport } from './routes/_header'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeaderUsersIndexRouteImport } from './routes/_header/users/index'
import { Route as HeaderProjectsIndexRouteImport } from './routes/_header/projects/index'
import { Route as HeaderFilesIndexRouteImport } from './routes/_header/files/index'
import { Route as HeaderDashboardIndexRouteImport } from './routes/_header/dashboard/index'
import { Route as HeaderUsersAddUserRouteImport } from './routes/_header/users/add-user'
import { Route as HeaderProjectsNewProjectRouteImport } from './routes/_header/projects/new-project'
import { Route as HeaderFilesNewFileRouteImport } from './routes/_header/files/new-file'

const HeaderRoute = HeaderRouteImport.update({
  id: '/_header',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderUsersIndexRoute = HeaderUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => HeaderRoute,
} as any)
const HeaderProjectsIndexRoute = HeaderProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => HeaderRoute,
} as any)
const HeaderFilesIndexRoute = HeaderFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => HeaderRoute,
} as any)
const HeaderDashboardIndexRoute = HeaderDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => HeaderRoute,
} as any)
const HeaderUsersAddUserRoute = HeaderUsersAddUserRouteImport.update({
  id: '/users/add-user',
  path: '/users/add-user',
  getParentRoute: () => HeaderRoute,
} as any)
const HeaderProjectsNewProjectRoute =
  HeaderProjectsNewProjectRouteImport.update({
    id: '/projects/new-project',
    path: '/projects/new-project',
    getParentRoute: () => HeaderRoute,
  } as any)
const HeaderFilesNewFileRoute = HeaderFilesNewFileRouteImport.update({
  id: '/files/new-file',
  path: '/files/new-file',
  getParentRoute: () => HeaderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files/new-file': typeof HeaderFilesNewFileRoute
  '/projects/new-project': typeof HeaderProjectsNewProjectRoute
  '/users/add-user': typeof HeaderUsersAddUserRoute
  '/dashboard': typeof HeaderDashboardIndexRoute
  '/files': typeof HeaderFilesIndexRoute
  '/projects': typeof HeaderProjectsIndexRoute
  '/users': typeof HeaderUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files/new-file': typeof HeaderFilesNewFileRoute
  '/projects/new-project': typeof HeaderProjectsNewProjectRoute
  '/users/add-user': typeof HeaderUsersAddUserRoute
  '/dashboard': typeof HeaderDashboardIndexRoute
  '/files': typeof HeaderFilesIndexRoute
  '/projects': typeof HeaderProjectsIndexRoute
  '/users': typeof HeaderUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_header': typeof HeaderRouteWithChildren
  '/_header/files/new-file': typeof HeaderFilesNewFileRoute
  '/_header/projects/new-project': typeof HeaderProjectsNewProjectRoute
  '/_header/users/add-user': typeof HeaderUsersAddUserRoute
  '/_header/dashboard/': typeof HeaderDashboardIndexRoute
  '/_header/files/': typeof HeaderFilesIndexRoute
  '/_header/projects/': typeof HeaderProjectsIndexRoute
  '/_header/users/': typeof HeaderUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files/new-file'
    | '/projects/new-project'
    | '/users/add-user'
    | '/dashboard'
    | '/files'
    | '/projects'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files/new-file'
    | '/projects/new-project'
    | '/users/add-user'
    | '/dashboard'
    | '/files'
    | '/projects'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_header'
    | '/_header/files/new-file'
    | '/_header/projects/new-project'
    | '/_header/users/add-user'
    | '/_header/dashboard/'
    | '/_header/files/'
    | '/_header/projects/'
    | '/_header/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeaderRoute: typeof HeaderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_header': {
      id: '/_header'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header/users/': {
      id: '/_header/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof HeaderUsersIndexRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/projects/': {
      id: '/_header/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof HeaderProjectsIndexRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/files/': {
      id: '/_header/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof HeaderFilesIndexRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/dashboard/': {
      id: '/_header/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HeaderDashboardIndexRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/users/add-user': {
      id: '/_header/users/add-user'
      path: '/users/add-user'
      fullPath: '/users/add-user'
      preLoaderRoute: typeof HeaderUsersAddUserRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/projects/new-project': {
      id: '/_header/projects/new-project'
      path: '/projects/new-project'
      fullPath: '/projects/new-project'
      preLoaderRoute: typeof HeaderProjectsNewProjectRouteImport
      parentRoute: typeof HeaderRoute
    }
    '/_header/files/new-file': {
      id: '/_header/files/new-file'
      path: '/files/new-file'
      fullPath: '/files/new-file'
      preLoaderRoute: typeof HeaderFilesNewFileRouteImport
      parentRoute: typeof HeaderRoute
    }
  }
}

interface HeaderRouteChildren {
  HeaderFilesNewFileRoute: typeof HeaderFilesNewFileRoute
  HeaderProjectsNewProjectRoute: typeof HeaderProjectsNewProjectRoute
  HeaderUsersAddUserRoute: typeof HeaderUsersAddUserRoute
  HeaderDashboardIndexRoute: typeof HeaderDashboardIndexRoute
  HeaderFilesIndexRoute: typeof HeaderFilesIndexRoute
  HeaderProjectsIndexRoute: typeof HeaderProjectsIndexRoute
  HeaderUsersIndexRoute: typeof HeaderUsersIndexRoute
}

const HeaderRouteChildren: HeaderRouteChildren = {
  HeaderFilesNewFileRoute: HeaderFilesNewFileRoute,
  HeaderProjectsNewProjectRoute: HeaderProjectsNewProjectRoute,
  HeaderUsersAddUserRoute: HeaderUsersAddUserRoute,
  HeaderDashboardIndexRoute: HeaderDashboardIndexRoute,
  HeaderFilesIndexRoute: HeaderFilesIndexRoute,
  HeaderProjectsIndexRoute: HeaderProjectsIndexRoute,
  HeaderUsersIndexRoute: HeaderUsersIndexRoute,
}

const HeaderRouteWithChildren =
  HeaderRoute._addFileChildren(HeaderRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeaderRoute: HeaderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
